on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - run: "echo job ${{ github.job}}"
  debug:
    runs-on: ubuntu-latest
    needs: check
    steps:
    - run: "echo Job ${{ github.job }}"

  runs:
    runs-on: ubuntu-latest
    needs: debug
    steps:
    - run: "echo Job ${{ github.job }}"

  upload: 
    runs-on: ubuntu-latest
    needs: [debug,runs]
    steps:
    - run: "echo Job ${{ github.job }}"
    
